import { useEffect, useState } from "react"
import { Alert, Avatar, Box, Button, Card, CardContent, CircularProgress, Drawer, Grid, IconButton, List, ListItem, ListItemIcon, ListItemText, MenuItem, Select, TextField, Typography } from "@mui/material"
import { Add, Business, Dashboard, Engineering, History, Inventory2, LockReset, Logout, Menu, Nfc, PersonAdd, QrCode2, Send } from "@mui/icons-material"
import { useLocation, useNavigate } from "react-router-dom"
import { apiService, type PasswordResetResponse, type Unit } from "../services/apiService"
import { authService } from "../services/authService"
import MultiUnitSelect from "./MultiUnitSelect"

const DRAWER_WIDTH = 240
type Form = { username: string; first_name: string; last_name: string; email: string; profile_type: string; unidades: number[] }
type Errors = Partial<Record<keyof Form, string>>
const profiles = [{ value: 1, label: "Key User" }, { value: 2, label: "Supervisor" }, { value: 4, label: "Visualização" }, { value: 5, label: "Central Remota" }]

export default function CreateCloudAccessUser() {
  const navigate = useNavigate(); const location = useLocation(); const enabled = authService.shouldEnableFeatures()
  const [mobileOpen, setMobileOpen] = useState(false); const [units, setUnits] = useState<Unit[]>([]); const [loadingUnits, setLoadingUnits] = useState(true); const [submitting, setSubmitting] = useState(false)
  const [form, setForm] = useState<Form>({ username: "", first_name: "", last_name: "", email: "", profile_type: "", unidades: [] }); const [errors, setErrors] = useState<Errors>({}); const [error, setError] = useState<string | null>(null); const [result, setResult] = useState<PasswordResetResponse | null>(null)
  const user = authService.getUserData()
  useEffect(() => { apiService.getUnits().then(setUnits).catch(() => setError("Não foi possível carregar as unidades. Tente novamente.")).finally(() => setLoadingUnits(false)) }, [])
  const setField = (field: Exclude<keyof Form, "unidades">, value: string) => { setForm((current) => ({ ...current, [field]: value })); setErrors((current) => ({ ...current, [field]: undefined })) }
  const validate = () => { const next: Errors = {}; (["username", "first_name", "last_name", "email", "profile_type"] as const).forEach((field) => { if (!form[field].trim()) next[field] = "Este campo é obrigatório." }); if (!form.unidades.length) next.unidades = "Selecione pelo menos uma unidade."; setErrors(next); return !Object.keys(next).length }
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setError(null); setResult(null); if (!validate()) return; setSubmitting(true); try { const response = await apiService.createCloudAccessUser({ username: form.username.trim(), first_name: form.first_name.trim(), last_name: form.last_name.trim(), email: form.email.trim(), profile_type: Number(form.profile_type), unidades: form.unidades }); setResult(response); setForm({ username: "", first_name: "", last_name: "", email: "", profile_type: "", unidades: [] }) } catch (requestError) { setError(requestError instanceof Error ? requestError.message : "Não foi possível criar o usuário.") } finally { setSubmitting(false) } }
  const items = [{ label: "Dashboard", path: "/", icon: <Dashboard />, enabled: true }, { label: "Nova Tarefa", path: "/nova-tarefa", icon: <Add />, enabled }, { label: "Histórico", path: "/historico", icon: <History />, enabled }, { label: "Unidades", path: "/unidades", icon: <Business />, enabled }, { label: "Inventário", path: "/inventario", icon: <Inventory2 />, enabled }, { label: "QRCode", path: "/qrcode", icon: <QrCode2 />, enabled }, { label: "RFID", path: "/rfid", icon: <Nfc />, enabled }, { label: "Reset de Senha", path: "/reset-senha-cloudaccess", icon: <LockReset />, enabled }, { label: "Criar Usuário CloudAccess", path: "/criar-usuario-cloudaccess", icon: <PersonAdd />, enabled }]
  const drawer = <Box sx={{ height: "100%", bgcolor: "#1a1a1a", color: "white" }}><Box sx={{ p: 3, borderBottom: "1px solid #333", display: "flex", gap: 2, alignItems: "center" }}><Engineering sx={{ fontSize: 32, color: "#2196f3" }} /><Typography variant="h6">GerecTech</Typography></Box><List sx={{ px: 2, py: 1 }}>{items.map((item, index) => { const active = location.pathname === item.path; return <Box key={item.path}>{index === 5 && <Box sx={{ borderTop: "1px solid #333", my: 2 }} />}<ListItem onClick={() => item.enabled && navigate(item.path)} sx={{ borderRadius: 2, mb: 1, bgcolor: active ? "#2196f3" : "transparent", cursor: item.enabled ? "pointer" : "not-allowed", opacity: item.enabled ? 1 : .5 }}><ListItemIcon sx={{ color: active ? "white" : "#ccc" }}>{item.icon}</ListItemIcon><ListItemText primary={item.label} primaryTypographyProps={{ fontSize: ".9rem", color: active ? "white" : "#ccc" }} /></ListItem></Box> })}<Box sx={{ borderTop: "1px solid #333", my: 2 }} /><ListItem onClick={() => authService.logout()} sx={{ cursor: "pointer", borderRadius: 2 }}><ListItemIcon><Logout sx={{ color: "#ccc" }} /></ListItemIcon><ListItemText primary="Sair" primaryTypographyProps={{ color: "#ccc" }} /></ListItem></List></Box>
  return <Box sx={{ display: "flex", minHeight: "100vh", bgcolor: "#f8f9fa" }}><Box sx={{ width: DRAWER_WIDTH, display: { xs: "none", md: "block" } }}>{drawer}</Box><Drawer open={mobileOpen} onClose={() => setMobileOpen(false)} sx={{ display: { md: "none" }, "& .MuiDrawer-paper": { width: DRAWER_WIDTH } }}>{drawer}</Drawer><Box sx={{ flexGrow: 1 }}><Box sx={{ p: 3, bgcolor: "white", display: "flex", justifyContent: "space-between", alignItems: "center", borderBottom: "1px solid #e0e0e0" }}><Box sx={{ display: "flex", gap: 2, alignItems: "center" }}><IconButton sx={{ display: { md: "none" } }} onClick={() => setMobileOpen(true)}><Menu /></IconButton><Typography variant="h5">Criar Usuário CloudAccess</Typography></Box><Avatar>{user?.username?.charAt(0) || "U"}</Avatar></Box><Box sx={{ maxWidth: 760, mx: "auto", p: 3 }}><Card><CardContent sx={{ p: 4 }}><Typography variant="h6" sx={{ mb: 3 }}>Cadastro de usuário</Typography>{error && <Alert severity="error" sx={{ mb: 3 }}>{error}</Alert>}{result && <Result result={result} onClose={() => setResult(null)} />}<Box component="form" onSubmit={submit} noValidate><Grid container spacing={3}>{([ ["username", "Username"], ["first_name", "Primeiro Nome"], ["last_name", "Sobrenome"], ["email", "E-mail"] ] as const).map(([field, label]) => <Grid item xs={12} sm={6} key={field}><TextField fullWidth type={field === "email" ? "email" : "text"} label={label} value={form[field]} disabled={submitting} error={Boolean(errors[field])} helperText={errors[field]} onChange={(event) => setField(field, event.target.value)} /></Grid>)}<Grid item xs={12}><Select fullWidth displayEmpty value={form.profile_type} disabled={submitting} error={Boolean(errors.profile_type)} onChange={(event) => setField("profile_type", event.target.value)}><MenuItem value="" disabled>Tipo de Perfil</MenuItem>{profiles.map((profile) => <MenuItem key={profile.value} value={String(profile.value)}>{profile.label}</MenuItem>)}</Select>{errors.profile_type && <Typography variant="caption" color="error">{errors.profile_type}</Typography>}</Grid><Grid item xs={12}><MultiUnitSelect units={units} value={form.unidades} disabled={loadingUnits || submitting} error={errors.unidades} onChange={(unidades) => { setForm((current) => ({ ...current, unidades })); setErrors((current) => ({ ...current, unidades: undefined })) }} /></Grid><Grid item xs={12}><Button type="submit" variant="contained" disabled={submitting || loadingUnits} startIcon={submitting ? <CircularProgress size={18} color="inherit" /> : <Send />}>{submitting ? "Criando usuário..." : "Criar Usuário"}</Button></Grid></Grid></Box></CardContent></Card></Box></Box></Box>
}

function Result({ result, onClose }: { result: PasswordResetResponse; onClose: () => void }) { const { unidades_ok: ok, unidades_fail: fail } = result.detail; return <Box sx={{ mb: 3 }}>{<Alert severity={fail.length ? (ok.length ? "warning" : "error") : "success"} onClose={onClose} sx={{ mb: 2 }}>{fail.length ? (ok.length ? "Usuário criado parcialmente." : "Nenhum usuário foi criado.") : `Usuário criado com sucesso em ${ok.length} unidade(s).`}</Alert>}{ok.length > 0 && <Box sx={{ mb: 2 }}><Typography fontWeight={600}>Unidades processadas com sucesso</Typography>{ok.map((unit) => <Typography key={unit.unidade}>• Unidade {unit.garagem}</Typography>)}</Box>}{fail.length > 0 && <Box><Typography fontWeight={600} color="error">Unidades com erro</Typography>{fail.map((unit) => <Box key={unit.unidade} sx={{ mb: 1 }}><Typography>• Unidade {unit.garagem}</Typography><Typography color="error" variant="body2">{unit.erro}</Typography></Box>)}</Box>}</Box> }
